/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : bigint,
  'staffId' : bigint,
  'date' : string,
  'isEarlyExit' : boolean,
  'isLate' : boolean,
  'checkInTime' : [] | [bigint],
  'checkOutTime' : [] | [bigint],
  'overtimeMinutes' : bigint,
}
export interface EarningsEntry {
  'id' : bigint,
  'total' : bigint,
  'staffId' : bigint,
  'date' : string,
  'parts' : Array<bigint>,
}
export interface NotificationEvent {
  'id' : bigint,
  'staffName' : string,
  'staffId' : bigint,
  'message' : string,
  'timestamp' : bigint,
  'eventType' : { 'checkIn' : null } |
    { 'checkOut' : null },
}
export interface StaffProfile {
  'id' : bigint,
  'isPremium' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'photoUrl' : string,
  'isActive' : boolean,
  'shiftStart' : string,
  'shiftEnd' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateEarningsEntry' : ActorMethod<
    [bigint, string, Array<bigint>],
    bigint
  >,
  'addStaff' : ActorMethod<[string, string, string, string, boolean], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkIn' : ActorMethod<[bigint], bigint>,
  'checkOut' : ActorMethod<[bigint], bigint>,
  'getAllStaff' : ActorMethod<[], Array<StaffProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEarningsByStaffAndMonth' : ActorMethod<
    [bigint, bigint, bigint],
    Array<EarningsEntry>
  >,
  'getRecentNotifications' : ActorMethod<[bigint], Array<NotificationEvent>>,
  'getStaffById' : ActorMethod<[bigint], StaffProfile>,
  'getTodayAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeStaff' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateStaff' : ActorMethod<
    [bigint, string, string, string, string, boolean, boolean],
    undefined
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];