/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StaffProfile = IDL.Record({
  'id' : IDL.Nat,
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'photoUrl' : IDL.Text,
  'isActive' : IDL.Bool,
  'shiftStart' : IDL.Text,
  'shiftEnd' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'staffId' : IDL.Nat,
  'date' : IDL.Text,
  'isEarlyExit' : IDL.Bool,
  'isLate' : IDL.Bool,
  'checkInTime' : IDL.Opt(IDL.Int),
  'checkOutTime' : IDL.Opt(IDL.Int),
  'overtimeMinutes' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const EarningsEntry = IDL.Record({
  'id' : IDL.Nat,
  'total' : IDL.Nat,
  'staffId' : IDL.Nat,
  'date' : IDL.Text,
  'parts' : IDL.Vec(IDL.Nat),
});
export const HalfDayRecord = IDL.Record({
  'id' : IDL.Nat,
  'staffId' : IDL.Nat,
  'date' : IDL.Text,
  'markedAt' : IDL.Int,
});
export const NotificationEvent = IDL.Record({
  'id' : IDL.Nat,
  'staffName' : IDL.Text,
  'staffId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'eventType' : IDL.Variant({ 'checkIn' : IDL.Null, 'checkOut' : IDL.Null }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateEarningsEntry' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'addStaff' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIn' : IDL.Func([IDL.Nat], [IDL.Int], []),
  'checkOut' : IDL.Func([IDL.Nat], [IDL.Int], []),
  'getAllStaff' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEarningsByStaffAndMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(EarningsEntry)],
      ['query'],
    ),
  'getHalfDaysByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HalfDayRecord)],
      ['query'],
    ),
  'getHalfDaysByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(HalfDayRecord)],
      ['query'],
    ),
  'getRecentNotifications' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(NotificationEvent)],
      ['query'],
    ),
  'getStaffById' : IDL.Func([IDL.Nat], [StaffProfile], ['query']),
  'getTodayAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markHalfDay' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'removeHalfDay' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'removeStaff' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateStaff' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StaffProfile = IDL.Record({
    'id' : IDL.Nat,
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'photoUrl' : IDL.Text,
    'isActive' : IDL.Bool,
    'shiftStart' : IDL.Text,
    'shiftEnd' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'staffId' : IDL.Nat,
    'date' : IDL.Text,
    'isEarlyExit' : IDL.Bool,
    'isLate' : IDL.Bool,
    'checkInTime' : IDL.Opt(IDL.Int),
    'checkOutTime' : IDL.Opt(IDL.Int),
    'overtimeMinutes' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const EarningsEntry = IDL.Record({
    'id' : IDL.Nat,
    'total' : IDL.Nat,
    'staffId' : IDL.Nat,
    'date' : IDL.Text,
    'parts' : IDL.Vec(IDL.Nat),
  });
  const HalfDayRecord = IDL.Record({
    'id' : IDL.Nat,
    'staffId' : IDL.Nat,
    'date' : IDL.Text,
    'markedAt' : IDL.Int,
  });
  const NotificationEvent = IDL.Record({
    'id' : IDL.Nat,
    'staffName' : IDL.Text,
    'staffId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'eventType' : IDL.Variant({ 'checkIn' : IDL.Null, 'checkOut' : IDL.Null }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateEarningsEntry' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'addStaff' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIn' : IDL.Func([IDL.Nat], [IDL.Int], []),
    'checkOut' : IDL.Func([IDL.Nat], [IDL.Int], []),
    'getAllStaff' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEarningsByStaffAndMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(EarningsEntry)],
        ['query'],
      ),
    'getHalfDaysByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HalfDayRecord)],
        ['query'],
      ),
    'getHalfDaysByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(HalfDayRecord)],
        ['query'],
      ),
    'getRecentNotifications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(NotificationEvent)],
        ['query'],
      ),
    'getStaffById' : IDL.Func([IDL.Nat], [StaffProfile], ['query']),
    'getTodayAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markHalfDay' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'removeHalfDay' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'removeStaff' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateStaff' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };